FROM node:lts-alpine AS build-stage

WORKDIR /app

COPY ./DevOpsTraining-frontend/package*.json ./

RUN npm install

COPY ./DevOpsTraining-frontend .

RUN npm run build

FROM nginx:stable-alpine AS production-stage

COPY --from=build-stage /app/dist /usr/share/nginx/html

CMD [ "nginx", "-g", "daemon off;" ]